version: '3.3'
services:
  db:
    build:
      context: .
      dockerfile: imdb.Dockerfile
    image: 'mysql:8'
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: imdb
    ports:
      - '127.0.0.1:3306:3306'
    security_opt:
      - 'seccomp:unconfined'
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:8080:8080'
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: imdb
      DB_USER: root
      DB_PASSWORD: secret
    depends_on:
      - db
